vars:
  APP_VERSION:
    default: 0.0.0

platforms:
  android:
    incrementVersionCode: true
    versionName: $APP_VERSION
  ios:
    targets:
      App:
        incrementBuild: true
        version: $APP_VERSION
