vars:
  FIELD_NOTES_VERSION_NUMBER:
  FIELD_NOTES_BUILD_NUMBER:

platforms:
  android:
    versionCode: $FIELD_NOTES_BUILD_NUMBER
    versionName: $FIELD_NOTES_VERSION_NUMBER
  ios:
    targets:
      App:
        buildNumber: $FIELD_NOTES_BUILD_NUMBER
        version: $FIELD_NOTES_VERSION_NUMBER
      App_Prod:
        buildNumber: $FIELD_NOTES_BUILD_NUMBER
        version: $FIELD_NOTES_VERSION_NUMBER
